image: corise/dbt-course-gitpod
tasks:
  - init: |
      ./gitpod-init.sh
    command: |
      ./gitpod-command.sh
ports:
  - port: 8000
    onOpen: open-browser
  - port: 8081
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
vscode:
  extensions:
    - cweijan.vscode-database-client2
