version: 2

models:
  - name: dim_users
    columns:
      - name: user_id
        tests: 
          - unique
          - not_null
  - name: fact_orders
    columns:
        - name: order_id
          tests: 
            - unique
            - not_null